##
##  ci.yml
##  Stories
##
##  Created by Ariel Elkin on 2022/07/09.
##  Copyright My Balls. All rights reserved.
##

name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-site:
    name: Build
    runs-on:  macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.154.5"
          extended: true

      - name: Build site
        run: |
          hugo build

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Check site
        run: |
          NOKOGIRI_USE_SYSTEM_LIBRARIES=true
          gem install html-proofer --silent
          htmlproofer --ignore-urls "/leonardo.ai/,/instagram.com/,/midjourney.com/,/twitter.com/,/reddit.com/,/substack.com/,/chatgpt.com/,/openai.com/,/claude.ai/" ./docs
